### ISSUE TITLE
Misleading 403 instead of 404 for non-existent resource in data service download

### ISSUE THREAD

**Issue by sebplorenz** [FIWARE/VCVerifier#44]
I'm trying to get the resource http://{{dataServiceUrl}}/ngsi-ld/v1/entities/urn:ngsi-ld:EnergyReport:fms-1

If the resource is not created in advance, a 403-Forbidden is returned. Which is misleading.

Expected: 404-Not Found.

**Comment by wistefan** [comment]
@sebplorenz Could you please share more details about your config? I dont fully understand the issue

**Comment by sebplorenz** [comment]
Sorry, wrong component.
